### ISSUE TITLE
No possibility to unsubscribe from a deleted channel

### ISSUE THREAD

**Issue by frabnet** [notify-events/push-app#2]
I deleted a channel from the website.
It was still was configured in the Android application.
I try to delete from the application it but there is no way to do it.
Also, when opening a non existing channel, 404 error shows up.
<img src="https://user-images.githubusercontent.com/26867706/126524482-ba49d67a-cec6-46eb-ad8e-df3c241d74de.jpg" width="320">
The behaviour of course is normal, but I think it should be allowed to delete it in some way.
Thank you for your work.

**Comment by papajojo** [comment]
Hello, @frabnet

Thank you for your report! We've actually found and fixed a bug on the backend side (so you dont have to update the app). 
Our team would be happy to reward you with some bonus messages if you could share your Notify.Events login :)

Thank you for your interest in our service!

**Comment by frabnet** [comment]
Ok. Now it shows the same error only one time, then the channel disappear from the App. Guess it's fixed!
Thank you for the reward, my Notify.Events login is "frabattista".
